// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package model

import (
	"database/sql"
)

type ImgItem struct {
	ID          int64  `db:"id"`
	RefMeta     int64  `db:"ref_meta"`
	Data        []byte `db:"data"`
	Hash        string `db:"hash"`
	ContentType string `db:"content_type"`
	Url         string `db:"url"`
}

type ImgItemFailed struct {
	ID        int64  `db:"id"`
	RefMeta   int64  `db:"ref_meta"`
	FailedUrl string `db:"failed_url"`
	Hash      string `db:"hash"`
}

type ImgItemPv struct {
	RefItem int64          `db:"ref_item"`
	Data    sql.NullString `db:"data"`
}

type ImgSetMetum struct {
	ID        int64  `db:"id"`
	Title     string `db:"title"`
	OriginUrl string `db:"origin_url"`
	Hash      string `db:"hash"`
}
